#!/usr/bin/env bash
# Commands to install nginx on a web server 

sudo apt-get update
sudo apt-get install nginx 
sudo ufw 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

#testing nginx configuration
sudo nginx -t
sudo service nginx reload
